#pragma once

#define DEF_TIMEZONE_GREENWICH			0
#define DEF_TIMEZONE_BEIJING			8
#define MILLISECONDS_NANOSECOND100		((ULONGLONG)1000*10)
#define SECOND_NANOSECOND100			((ULONGLONG)1000*MILLISECONDS_NANOSECOND100)
#define MINUTE_NANASECOND100			((ULONGLONG)60*SECOND_NANOSECOND100)
#define HOUR_NANOSECOND100				((ULONGLONG)60*MINUTE_NANASECOND100)

BOOL ToSystemTimeFormat(ULONGLONG nUTC, LPSYSTEMTIME lpST);
ULONGLONG ToTimeZone(ULONGLONG nUTC, int nZone);
ULONGLONG ScanTimeString(LPCWSTR lpwsTimeString);
ULONGLONG ToCRTTime(ULONGLONG uTime);
ULONGLONG FromCRTTime(ULONGLONG uTime);
LPCWSTR GetMonthEN(DWORD dwMonth);
LPCWSTR GetDayEN(DWORD dwDay);
LPCWSTR GetWeekDay( DWORD dwWeek );
LPCWSTR GetWeekDayUpWord( DWORD dwWeek );
BOOL IsSameDay(ULONGLONG uTime1, ULONGLONG uTime2);
BOOL IsToday(ULONGLONG uTime, ULONGLONG uNowUTC);
BOOL IsTomorrow(ULONGLONG uTime, ULONGLONG uNowUTC);
BOOL IsAfterTomorrow(ULONGLONG uTime, ULONGLONG uNowUTC);
time_t SystemTime2Time_t(SYSTEMTIME& systime);